spring.application.name=journalApp
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://jyotsna:jyotsna@cluster0.pv8eiqa.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.auto-index-creation=true

